apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: circuit-breaker-for-staff-service
spec:
  host: fleetman-staff-service.default.svc.cluster.local
  trafficPolicy:
    outlierDetection: # Circuit Breaker have to switched on manually
      maxEjectionPercent: 100